volumes:
  dev-db-volume: {}
services:
  dev-pg12:
    container_name: tracker
    hostname: hostracker
    image: bitnami/postgresql:17.2.0
    environment:
      POSTGRESQL_DATABASE: tracker
      POSTGRESQL_USERNAME: admin
      POSTGRESQL_PASSWORD: admin
    volumes:
      - dev-db-volume:/bitnami/postgresql
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eoeqs"]
      interval: 5s
      timeout: 5s
      retries: 3